# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# DGen/SDL v1.26+

# Tell how to make assembler files


pkgdatadir = $(datadir)/dgen-sdl
pkgincludedir = $(includedir)/dgen-sdl
pkglibdir = $(libdir)/dgen-sdl
pkglibexecdir = $(libexecdir)/dgen-sdl
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = armv6l-unknown-linux-gnueabi
host_triplet = armv6l-unknown-linux-gnueabi
target_triplet = armv6l-unknown-linux-gnueabi
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/Makefile.asm.am \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	config.guess config.sub depcomp install-sh missing

# Musashi
am__append_1 = musa
am__append_2 = musa/libmusa68.a
am__append_3 = musa/libmusa68.a

# MZ80
am__append_4 = mz80
am__append_5 = mz80/libmz80.a
am__append_6 = mz80/libmz80.a

# StarScream
#am__append_7 = star
#am__append_8 = star/libstarcpu.a
#am__append_9 = star/libstarcpu.a

# Cyclone 68000
am__append_10 = cyclone
am__append_11 = cyclone/libcyclonecpu.a
am__append_12 = cyclone/libcyclonecpu.a
bin_PROGRAMS = dgen$(EXEEXT) dgen_tobin$(EXEEXT)

# debugger
#am__append_13 = -DUSE_UTF8
#am__append_14 = \
#	debug.cpp		\
#	linenoise/linenoise.h	\
#	linenoise/linenoise.c	\
#	linenoise/utf8.c


# CZ80
am__append_15 = -I$(top_srcdir)/cz80
am__append_16 = cz80/cz80.c

# DrZ80
am__append_17 = -I$(top_srcdir)/drz80
am__append_18 = drz80/drz80.s

# hqx
am__append_19 = -I$(top_srcdir)/hqx/src -DHQX_NO_CALLCONV -DHQX_NO_API
am__append_20 = \
	hqx/src/init.c		\
	hqx/src/hq2x_32.c	\
	hqx/src/hq2x_24.c	\
	hqx/src/hq2x_16.c	\
	hqx/src/hq2x-int.h	\
	hqx/src/hq3x_32.c	\
	hqx/src/hq3x_24.c	\
	hqx/src/hq3x_16.c	\
	hqx/src/hq3x-int.h	\
	hqx/src/hq4x_32.c	\
	hqx/src/hq4x_24.c	\
	hqx/src/hq4x_16.c	\
	hqx/src/hq4x-int.h	\
	hqx/src/hqx.h		\
	hqx/src/common.h


# scale2x
am__append_21 = -I$(top_srcdir)/scale2x
am__append_22 = \
	scale2x/scale2x.c	\
	scale2x/scale2x.h	\
	scale2x/scale3x.c	\
	scale2x/scale3x.h	\
	scale2x/scalebit.c	\
	scale2x/scalebit.h

#am__append_23 = x86_tiles.asm
#am__append_24 = x86_ctv.asm
##am__append_25 = x86_mmx_memcpy.asm
#am__append_26 = x86_memcpy.asm
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" \
	"$(DESTDIR)$(man5dir)"
PROGRAMS = $(bin_PROGRAMS)
am__dgen_SOURCES_DIST = rc.h rc-vars.h rc.cpp romload.c md.h md.cpp \
	mdfr.cpp decode.h decode.c vdp.cpp save.cpp graph.cpp fm.h \
	fm.c myfm.cpp sn76496.h sn76496.c ras-drawplane.h ras.cpp \
	main.cpp mem.cpp pd.h ckvp.c ckvp.h joystick.cpp system.c \
	debug.cpp linenoise/linenoise.h linenoise/linenoise.c \
	linenoise/utf8.c cz80/cz80.c drz80/drz80.s hqx/src/init.c \
	hqx/src/hq2x_32.c hqx/src/hq2x_24.c hqx/src/hq2x_16.c \
	hqx/src/hq2x-int.h hqx/src/hq3x_32.c hqx/src/hq3x_24.c \
	hqx/src/hq3x_16.c hqx/src/hq3x-int.h hqx/src/hq4x_32.c \
	hqx/src/hq4x_24.c hqx/src/hq4x_16.c hqx/src/hq4x-int.h \
	hqx/src/hqx.h hqx/src/common.h scale2x/scale2x.c \
	scale2x/scale2x.h scale2x/scale3x.c scale2x/scale3x.h \
	scale2x/scalebit.c scale2x/scalebit.h x86_tiles.asm \
	x86_ctv.asm x86_mmx_memcpy.asm x86_memcpy.asm
#am__objects_1 = debug.$(OBJEXT) \
#	linenoise.$(OBJEXT) utf8.$(OBJEXT)
am__objects_2 = cz80.$(OBJEXT)
am__objects_3 = drz80.$(OBJEXT)
am__objects_4 = init.$(OBJEXT) hq2x_32.$(OBJEXT) \
	hq2x_24.$(OBJEXT) hq2x_16.$(OBJEXT) \
	hq3x_32.$(OBJEXT) hq3x_24.$(OBJEXT) \
	hq3x_16.$(OBJEXT) hq4x_32.$(OBJEXT) \
	hq4x_24.$(OBJEXT) hq4x_16.$(OBJEXT)
am__objects_5 = scale2x.$(OBJEXT) scale3x.$(OBJEXT) \
	scalebit.$(OBJEXT)
#am__objects_6 = x86_tiles.$(OBJEXT)
#am__objects_7 = x86_ctv.$(OBJEXT)
##am__objects_8 = x86_mmx_memcpy.$(OBJEXT)
#am__objects_9 =  \
#	x86_memcpy.$(OBJEXT)
am_dgen_OBJECTS = rc.$(OBJEXT) romload.$(OBJEXT) md.$(OBJEXT) \
	mdfr.$(OBJEXT) decode.$(OBJEXT) vdp.$(OBJEXT) save.$(OBJEXT) \
	graph.$(OBJEXT) fm.$(OBJEXT) myfm.$(OBJEXT) sn76496.$(OBJEXT) \
	ras.$(OBJEXT) main.$(OBJEXT) mem.$(OBJEXT) ckvp.$(OBJEXT) \
	joystick.$(OBJEXT) system.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_9)
dgen_OBJECTS = $(am_dgen_OBJECTS)
am__DEPENDENCIES_1 =
am_dgen_tobin_OBJECTS = tobin.$(OBJEXT) romload.$(OBJEXT) \
	system.$(OBJEXT)
dgen_tobin_OBJECTS = $(am_dgen_tobin_OBJECTS)
dgen_tobin_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX   " $@;
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD " $@;
CCASCOMPILE = $(CCAS) $(AM_CCASFLAGS) $(CCASFLAGS)
AM_V_CCAS = $(am__v_CCAS_$(V))
am__v_CCAS_ = $(am__v_CCAS_$(AM_DEFAULT_VERBOSITY))
am__v_CCAS_0 = @echo "  CCAS  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(dgen_SOURCES) $(dgen_tobin_SOURCES)
DIST_SOURCES = $(am__dgen_SOURCES_DIST) $(dgen_tobin_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
man1dir = $(mandir)/man1
man5dir = $(mandir)/man5
NROFF = nroff
MANS = $(man_MANS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run tar
AM_DEFAULT_VERBOSITY = 0
AUTOCONF = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run autoconf
AUTOHEADER = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run autoheader
AUTOMAKE = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run automake-1.11
AWK = mawk
CC = gcc -std=gnu99
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CC_FOR_BUILD = gcc -std=gnu99
CFLAGS = -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
CFLAGS_B = CFLAGS
CFLAGS_FOR_BUILD = -g -O2
CPP = gcc -std=gnu99 -E
CPPFLAGS =  -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
CPPFLAGS_B = CPPFLAGS
CPPFLAGS_FOR_BUILD = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CXXFLAGS_B = CXXFLAGS
CXXFLAGS_FOR_BUILD = -g -O2
CXX_FOR_BUILD = g++
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"DGen/SDL\" -DPACKAGE_TARNAME=\"dgen-sdl\" -DPACKAGE_VERSION=\"1.32\" -DPACKAGE_STRING=\"DGen/SDL\ 1.32\" -DPACKAGE_BUGREPORT=\"zamaz@users.sourceforge.net\" -DPACKAGE_URL=\"http://sourceforge.net/projects/dgen\" -DPACKAGE=\"dgen-sdl\" -DVERSION=\"1.32\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SDL_WM_TOGGLEFULLSCREEN=1 -DHAVE_FTELLO=1 -DHAVE_GLOB_H=1 -DWITH_LIBARCHIVE=1 -DNDEBUG=1 -DWITH_JOYSTICK=1 -DWITH_THREADS=1 -DWITH_MUSA=1 -DWITH_MZ80=1 -DWITH_CZ80=1 -DWITH_DRZ80=1 -DWITH_CYCLONE=1 -DWITH_ASM=1 -DWITH_CTV=1 -DWITH_HQX=1 -DWITH_SCALE2X=1
DEPDIR = .deps
DGEN_LIBS = -larchive  -L/usr/lib/arm-linux-gnueabihf -lSDL
DOXYGEN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
EXEEXT_FOR_BUILD = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LDFLAGS_B = LDFLAGS
LDFLAGS_FOR_BUILD = 
LIBOBJS = 
LIBS = -larchive  
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NASM = 
NASM_FORMAT = 
OBJEXT = o
OBJEXT_FOR_BUILD = o
PACKAGE = dgen-sdl
PACKAGE_BUGREPORT = zamaz@users.sourceforge.net
PACKAGE_NAME = DGen/SDL
PACKAGE_STRING = DGen/SDL 1.32
PACKAGE_TARNAME = dgen-sdl
PACKAGE_URL = http://sourceforge.net/projects/dgen
PACKAGE_VERSION = 1.32
PATH_SEPARATOR = :
RANLIB = ranlib
SDL_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_CONFIG = /usr/bin/sdl-config
SDL_LIBS = -L/usr/lib/arm-linux-gnueabihf -lSDL
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.32
abs_builddir = /home/pi/pimame/emulators/dgen-sdl-1.32
abs_srcdir = /home/pi/pimame/emulators/dgen-sdl-1.32
abs_top_builddir = /home/pi/pimame/emulators/dgen-sdl-1.32
abs_top_srcdir = /home/pi/pimame/emulators/dgen-sdl-1.32
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = armv6l-unknown-linux-gnueabi
build_alias = 
build_cpu = armv6l
build_os = linux-gnueabi
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = armv6l-unknown-linux-gnueabi
host_alias = 
host_cpu = armv6l
host_os = linux-gnueabi
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/pi/pimame/emulators/dgen-sdl-1.32/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = armv6l-unknown-linux-gnueabi
target_alias = 
target_cpu = armv6l
target_os = linux-gnueabi
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .
SUFFIXES = .asm
DIST_SUBDIRS = musa mz80 sdl star cyclone doc

# SDL

# DOCS
SUBDIRS = sdl $(am__append_1) $(am__append_4) doc $(am__append_7) \
	$(am__append_10)
AM_CPPFLAGS = -I$(top_srcdir) -I$(top_srcdir)/sdl $(am__append_13) \
	$(am__append_15) $(am__append_17) $(am__append_19) \
	$(am__append_21)
dgen_DEPENDENCIES = sdl/libpd.a $(am__append_2) $(am__append_5) \
	$(am__append_8) $(am__append_11)

# dgen
dgen_LDADD = sdl/libpd.a $(am__append_3) $(am__append_6) \
	$(am__append_9) $(am__append_12) $(DGEN_LIBS)
man_MANS = dgen.1 dgenrc.5 dgen_tobin.1
EXTRA_DIST = sample.dgenrc
dgen_SOURCES = rc.h rc-vars.h rc.cpp romload.c md.h md.cpp mdfr.cpp \
	decode.h decode.c vdp.cpp save.cpp graph.cpp fm.h fm.c \
	myfm.cpp sn76496.h sn76496.c ras-drawplane.h ras.cpp main.cpp \
	mem.cpp pd.h ckvp.c ckvp.h joystick.cpp system.c \
	$(am__append_14) $(am__append_16) $(am__append_18) \
	$(am__append_20) $(am__append_22) $(am__append_23) \
	$(am__append_24) $(am__append_25) $(am__append_26)

# dgen_tobin
dgen_tobin_SOURCES = tobin.c romload.c system.c
all: all-recursive

.SUFFIXES:
.SUFFIXES: .asm .$(OBJEXT) .c .cpp .o .obj .s
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/Makefile.asm.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
dgen$(EXEEXT): $(dgen_OBJECTS) $(dgen_DEPENDENCIES) 
	@rm -f dgen$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(dgen_OBJECTS) $(dgen_LDADD) $(LIBS)
dgen_tobin$(EXEEXT): $(dgen_tobin_OBJECTS) $(dgen_tobin_DEPENDENCIES) 
	@rm -f dgen_tobin$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(dgen_tobin_OBJECTS) $(dgen_tobin_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/ckvp.Po
include ./$(DEPDIR)/cz80.Po
include ./$(DEPDIR)/debug.Po
include ./$(DEPDIR)/decode.Po
include ./$(DEPDIR)/fm.Po
include ./$(DEPDIR)/graph.Po
include ./$(DEPDIR)/hq2x_16.Po
include ./$(DEPDIR)/hq2x_24.Po
include ./$(DEPDIR)/hq2x_32.Po
include ./$(DEPDIR)/hq3x_16.Po
include ./$(DEPDIR)/hq3x_24.Po
include ./$(DEPDIR)/hq3x_32.Po
include ./$(DEPDIR)/hq4x_16.Po
include ./$(DEPDIR)/hq4x_24.Po
include ./$(DEPDIR)/hq4x_32.Po
include ./$(DEPDIR)/init.Po
include ./$(DEPDIR)/joystick.Po
include ./$(DEPDIR)/linenoise.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/md.Po
include ./$(DEPDIR)/mdfr.Po
include ./$(DEPDIR)/mem.Po
include ./$(DEPDIR)/myfm.Po
include ./$(DEPDIR)/ras.Po
include ./$(DEPDIR)/rc.Po
include ./$(DEPDIR)/romload.Po
include ./$(DEPDIR)/save.Po
include ./$(DEPDIR)/scale2x.Po
include ./$(DEPDIR)/scale3x.Po
include ./$(DEPDIR)/scalebit.Po
include ./$(DEPDIR)/sn76496.Po
include ./$(DEPDIR)/system.Po
include ./$(DEPDIR)/tobin.Po
include ./$(DEPDIR)/utf8.Po
include ./$(DEPDIR)/vdp.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

linenoise.o: linenoise/linenoise.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT linenoise.o -MD -MP -MF $(DEPDIR)/linenoise.Tpo -c -o linenoise.o `test -f 'linenoise/linenoise.c' || echo '$(srcdir)/'`linenoise/linenoise.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/linenoise.Tpo $(DEPDIR)/linenoise.Po
#	$(AM_V_CC) \
#	source='linenoise/linenoise.c' object='linenoise.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linenoise.o `test -f 'linenoise/linenoise.c' || echo '$(srcdir)/'`linenoise/linenoise.c

linenoise.obj: linenoise/linenoise.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT linenoise.obj -MD -MP -MF $(DEPDIR)/linenoise.Tpo -c -o linenoise.obj `if test -f 'linenoise/linenoise.c'; then $(CYGPATH_W) 'linenoise/linenoise.c'; else $(CYGPATH_W) '$(srcdir)/linenoise/linenoise.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/linenoise.Tpo $(DEPDIR)/linenoise.Po
#	$(AM_V_CC) \
#	source='linenoise/linenoise.c' object='linenoise.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linenoise.obj `if test -f 'linenoise/linenoise.c'; then $(CYGPATH_W) 'linenoise/linenoise.c'; else $(CYGPATH_W) '$(srcdir)/linenoise/linenoise.c'; fi`

utf8.o: linenoise/utf8.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT utf8.o -MD -MP -MF $(DEPDIR)/utf8.Tpo -c -o utf8.o `test -f 'linenoise/utf8.c' || echo '$(srcdir)/'`linenoise/utf8.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/utf8.Tpo $(DEPDIR)/utf8.Po
#	$(AM_V_CC) \
#	source='linenoise/utf8.c' object='utf8.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o utf8.o `test -f 'linenoise/utf8.c' || echo '$(srcdir)/'`linenoise/utf8.c

utf8.obj: linenoise/utf8.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT utf8.obj -MD -MP -MF $(DEPDIR)/utf8.Tpo -c -o utf8.obj `if test -f 'linenoise/utf8.c'; then $(CYGPATH_W) 'linenoise/utf8.c'; else $(CYGPATH_W) '$(srcdir)/linenoise/utf8.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/utf8.Tpo $(DEPDIR)/utf8.Po
#	$(AM_V_CC) \
#	source='linenoise/utf8.c' object='utf8.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o utf8.obj `if test -f 'linenoise/utf8.c'; then $(CYGPATH_W) 'linenoise/utf8.c'; else $(CYGPATH_W) '$(srcdir)/linenoise/utf8.c'; fi`

cz80.o: cz80/cz80.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT cz80.o -MD -MP -MF $(DEPDIR)/cz80.Tpo -c -o cz80.o `test -f 'cz80/cz80.c' || echo '$(srcdir)/'`cz80/cz80.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cz80.Tpo $(DEPDIR)/cz80.Po
#	$(AM_V_CC) \
#	source='cz80/cz80.c' object='cz80.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o cz80.o `test -f 'cz80/cz80.c' || echo '$(srcdir)/'`cz80/cz80.c

cz80.obj: cz80/cz80.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT cz80.obj -MD -MP -MF $(DEPDIR)/cz80.Tpo -c -o cz80.obj `if test -f 'cz80/cz80.c'; then $(CYGPATH_W) 'cz80/cz80.c'; else $(CYGPATH_W) '$(srcdir)/cz80/cz80.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cz80.Tpo $(DEPDIR)/cz80.Po
#	$(AM_V_CC) \
#	source='cz80/cz80.c' object='cz80.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o cz80.obj `if test -f 'cz80/cz80.c'; then $(CYGPATH_W) 'cz80/cz80.c'; else $(CYGPATH_W) '$(srcdir)/cz80/cz80.c'; fi`

init.o: hqx/src/init.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT init.o -MD -MP -MF $(DEPDIR)/init.Tpo -c -o init.o `test -f 'hqx/src/init.c' || echo '$(srcdir)/'`hqx/src/init.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/init.Tpo $(DEPDIR)/init.Po
#	$(AM_V_CC) \
#	source='hqx/src/init.c' object='init.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o init.o `test -f 'hqx/src/init.c' || echo '$(srcdir)/'`hqx/src/init.c

init.obj: hqx/src/init.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT init.obj -MD -MP -MF $(DEPDIR)/init.Tpo -c -o init.obj `if test -f 'hqx/src/init.c'; then $(CYGPATH_W) 'hqx/src/init.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/init.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/init.Tpo $(DEPDIR)/init.Po
#	$(AM_V_CC) \
#	source='hqx/src/init.c' object='init.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o init.obj `if test -f 'hqx/src/init.c'; then $(CYGPATH_W) 'hqx/src/init.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/init.c'; fi`

hq2x_32.o: hqx/src/hq2x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_32.o -MD -MP -MF $(DEPDIR)/hq2x_32.Tpo -c -o hq2x_32.o `test -f 'hqx/src/hq2x_32.c' || echo '$(srcdir)/'`hqx/src/hq2x_32.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_32.Tpo $(DEPDIR)/hq2x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_32.c' object='hq2x_32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_32.o `test -f 'hqx/src/hq2x_32.c' || echo '$(srcdir)/'`hqx/src/hq2x_32.c

hq2x_32.obj: hqx/src/hq2x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_32.obj -MD -MP -MF $(DEPDIR)/hq2x_32.Tpo -c -o hq2x_32.obj `if test -f 'hqx/src/hq2x_32.c'; then $(CYGPATH_W) 'hqx/src/hq2x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_32.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_32.Tpo $(DEPDIR)/hq2x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_32.c' object='hq2x_32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_32.obj `if test -f 'hqx/src/hq2x_32.c'; then $(CYGPATH_W) 'hqx/src/hq2x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_32.c'; fi`

hq2x_24.o: hqx/src/hq2x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_24.o -MD -MP -MF $(DEPDIR)/hq2x_24.Tpo -c -o hq2x_24.o `test -f 'hqx/src/hq2x_24.c' || echo '$(srcdir)/'`hqx/src/hq2x_24.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_24.Tpo $(DEPDIR)/hq2x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_24.c' object='hq2x_24.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_24.o `test -f 'hqx/src/hq2x_24.c' || echo '$(srcdir)/'`hqx/src/hq2x_24.c

hq2x_24.obj: hqx/src/hq2x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_24.obj -MD -MP -MF $(DEPDIR)/hq2x_24.Tpo -c -o hq2x_24.obj `if test -f 'hqx/src/hq2x_24.c'; then $(CYGPATH_W) 'hqx/src/hq2x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_24.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_24.Tpo $(DEPDIR)/hq2x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_24.c' object='hq2x_24.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_24.obj `if test -f 'hqx/src/hq2x_24.c'; then $(CYGPATH_W) 'hqx/src/hq2x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_24.c'; fi`

hq2x_16.o: hqx/src/hq2x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_16.o -MD -MP -MF $(DEPDIR)/hq2x_16.Tpo -c -o hq2x_16.o `test -f 'hqx/src/hq2x_16.c' || echo '$(srcdir)/'`hqx/src/hq2x_16.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_16.Tpo $(DEPDIR)/hq2x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_16.c' object='hq2x_16.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_16.o `test -f 'hqx/src/hq2x_16.c' || echo '$(srcdir)/'`hqx/src/hq2x_16.c

hq2x_16.obj: hqx/src/hq2x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq2x_16.obj -MD -MP -MF $(DEPDIR)/hq2x_16.Tpo -c -o hq2x_16.obj `if test -f 'hqx/src/hq2x_16.c'; then $(CYGPATH_W) 'hqx/src/hq2x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_16.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq2x_16.Tpo $(DEPDIR)/hq2x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq2x_16.c' object='hq2x_16.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq2x_16.obj `if test -f 'hqx/src/hq2x_16.c'; then $(CYGPATH_W) 'hqx/src/hq2x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq2x_16.c'; fi`

hq3x_32.o: hqx/src/hq3x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_32.o -MD -MP -MF $(DEPDIR)/hq3x_32.Tpo -c -o hq3x_32.o `test -f 'hqx/src/hq3x_32.c' || echo '$(srcdir)/'`hqx/src/hq3x_32.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_32.Tpo $(DEPDIR)/hq3x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_32.c' object='hq3x_32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_32.o `test -f 'hqx/src/hq3x_32.c' || echo '$(srcdir)/'`hqx/src/hq3x_32.c

hq3x_32.obj: hqx/src/hq3x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_32.obj -MD -MP -MF $(DEPDIR)/hq3x_32.Tpo -c -o hq3x_32.obj `if test -f 'hqx/src/hq3x_32.c'; then $(CYGPATH_W) 'hqx/src/hq3x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_32.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_32.Tpo $(DEPDIR)/hq3x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_32.c' object='hq3x_32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_32.obj `if test -f 'hqx/src/hq3x_32.c'; then $(CYGPATH_W) 'hqx/src/hq3x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_32.c'; fi`

hq3x_24.o: hqx/src/hq3x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_24.o -MD -MP -MF $(DEPDIR)/hq3x_24.Tpo -c -o hq3x_24.o `test -f 'hqx/src/hq3x_24.c' || echo '$(srcdir)/'`hqx/src/hq3x_24.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_24.Tpo $(DEPDIR)/hq3x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_24.c' object='hq3x_24.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_24.o `test -f 'hqx/src/hq3x_24.c' || echo '$(srcdir)/'`hqx/src/hq3x_24.c

hq3x_24.obj: hqx/src/hq3x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_24.obj -MD -MP -MF $(DEPDIR)/hq3x_24.Tpo -c -o hq3x_24.obj `if test -f 'hqx/src/hq3x_24.c'; then $(CYGPATH_W) 'hqx/src/hq3x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_24.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_24.Tpo $(DEPDIR)/hq3x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_24.c' object='hq3x_24.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_24.obj `if test -f 'hqx/src/hq3x_24.c'; then $(CYGPATH_W) 'hqx/src/hq3x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_24.c'; fi`

hq3x_16.o: hqx/src/hq3x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_16.o -MD -MP -MF $(DEPDIR)/hq3x_16.Tpo -c -o hq3x_16.o `test -f 'hqx/src/hq3x_16.c' || echo '$(srcdir)/'`hqx/src/hq3x_16.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_16.Tpo $(DEPDIR)/hq3x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_16.c' object='hq3x_16.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_16.o `test -f 'hqx/src/hq3x_16.c' || echo '$(srcdir)/'`hqx/src/hq3x_16.c

hq3x_16.obj: hqx/src/hq3x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq3x_16.obj -MD -MP -MF $(DEPDIR)/hq3x_16.Tpo -c -o hq3x_16.obj `if test -f 'hqx/src/hq3x_16.c'; then $(CYGPATH_W) 'hqx/src/hq3x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_16.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq3x_16.Tpo $(DEPDIR)/hq3x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq3x_16.c' object='hq3x_16.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq3x_16.obj `if test -f 'hqx/src/hq3x_16.c'; then $(CYGPATH_W) 'hqx/src/hq3x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq3x_16.c'; fi`

hq4x_32.o: hqx/src/hq4x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_32.o -MD -MP -MF $(DEPDIR)/hq4x_32.Tpo -c -o hq4x_32.o `test -f 'hqx/src/hq4x_32.c' || echo '$(srcdir)/'`hqx/src/hq4x_32.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_32.Tpo $(DEPDIR)/hq4x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_32.c' object='hq4x_32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_32.o `test -f 'hqx/src/hq4x_32.c' || echo '$(srcdir)/'`hqx/src/hq4x_32.c

hq4x_32.obj: hqx/src/hq4x_32.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_32.obj -MD -MP -MF $(DEPDIR)/hq4x_32.Tpo -c -o hq4x_32.obj `if test -f 'hqx/src/hq4x_32.c'; then $(CYGPATH_W) 'hqx/src/hq4x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_32.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_32.Tpo $(DEPDIR)/hq4x_32.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_32.c' object='hq4x_32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_32.obj `if test -f 'hqx/src/hq4x_32.c'; then $(CYGPATH_W) 'hqx/src/hq4x_32.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_32.c'; fi`

hq4x_24.o: hqx/src/hq4x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_24.o -MD -MP -MF $(DEPDIR)/hq4x_24.Tpo -c -o hq4x_24.o `test -f 'hqx/src/hq4x_24.c' || echo '$(srcdir)/'`hqx/src/hq4x_24.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_24.Tpo $(DEPDIR)/hq4x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_24.c' object='hq4x_24.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_24.o `test -f 'hqx/src/hq4x_24.c' || echo '$(srcdir)/'`hqx/src/hq4x_24.c

hq4x_24.obj: hqx/src/hq4x_24.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_24.obj -MD -MP -MF $(DEPDIR)/hq4x_24.Tpo -c -o hq4x_24.obj `if test -f 'hqx/src/hq4x_24.c'; then $(CYGPATH_W) 'hqx/src/hq4x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_24.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_24.Tpo $(DEPDIR)/hq4x_24.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_24.c' object='hq4x_24.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_24.obj `if test -f 'hqx/src/hq4x_24.c'; then $(CYGPATH_W) 'hqx/src/hq4x_24.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_24.c'; fi`

hq4x_16.o: hqx/src/hq4x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_16.o -MD -MP -MF $(DEPDIR)/hq4x_16.Tpo -c -o hq4x_16.o `test -f 'hqx/src/hq4x_16.c' || echo '$(srcdir)/'`hqx/src/hq4x_16.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_16.Tpo $(DEPDIR)/hq4x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_16.c' object='hq4x_16.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_16.o `test -f 'hqx/src/hq4x_16.c' || echo '$(srcdir)/'`hqx/src/hq4x_16.c

hq4x_16.obj: hqx/src/hq4x_16.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hq4x_16.obj -MD -MP -MF $(DEPDIR)/hq4x_16.Tpo -c -o hq4x_16.obj `if test -f 'hqx/src/hq4x_16.c'; then $(CYGPATH_W) 'hqx/src/hq4x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_16.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/hq4x_16.Tpo $(DEPDIR)/hq4x_16.Po
#	$(AM_V_CC) \
#	source='hqx/src/hq4x_16.c' object='hq4x_16.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hq4x_16.obj `if test -f 'hqx/src/hq4x_16.c'; then $(CYGPATH_W) 'hqx/src/hq4x_16.c'; else $(CYGPATH_W) '$(srcdir)/hqx/src/hq4x_16.c'; fi`

scale2x.o: scale2x/scale2x.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scale2x.o -MD -MP -MF $(DEPDIR)/scale2x.Tpo -c -o scale2x.o `test -f 'scale2x/scale2x.c' || echo '$(srcdir)/'`scale2x/scale2x.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/scale2x.Tpo $(DEPDIR)/scale2x.Po
#	$(AM_V_CC) \
#	source='scale2x/scale2x.c' object='scale2x.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scale2x.o `test -f 'scale2x/scale2x.c' || echo '$(srcdir)/'`scale2x/scale2x.c

scale2x.obj: scale2x/scale2x.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scale2x.obj -MD -MP -MF $(DEPDIR)/scale2x.Tpo -c -o scale2x.obj `if test -f 'scale2x/scale2x.c'; then $(CYGPATH_W) 'scale2x/scale2x.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scale2x.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/scale2x.Tpo $(DEPDIR)/scale2x.Po
#	$(AM_V_CC) \
#	source='scale2x/scale2x.c' object='scale2x.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scale2x.obj `if test -f 'scale2x/scale2x.c'; then $(CYGPATH_W) 'scale2x/scale2x.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scale2x.c'; fi`

scale3x.o: scale2x/scale3x.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scale3x.o -MD -MP -MF $(DEPDIR)/scale3x.Tpo -c -o scale3x.o `test -f 'scale2x/scale3x.c' || echo '$(srcdir)/'`scale2x/scale3x.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/scale3x.Tpo $(DEPDIR)/scale3x.Po
#	$(AM_V_CC) \
#	source='scale2x/scale3x.c' object='scale3x.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scale3x.o `test -f 'scale2x/scale3x.c' || echo '$(srcdir)/'`scale2x/scale3x.c

scale3x.obj: scale2x/scale3x.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scale3x.obj -MD -MP -MF $(DEPDIR)/scale3x.Tpo -c -o scale3x.obj `if test -f 'scale2x/scale3x.c'; then $(CYGPATH_W) 'scale2x/scale3x.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scale3x.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/scale3x.Tpo $(DEPDIR)/scale3x.Po
#	$(AM_V_CC) \
#	source='scale2x/scale3x.c' object='scale3x.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scale3x.obj `if test -f 'scale2x/scale3x.c'; then $(CYGPATH_W) 'scale2x/scale3x.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scale3x.c'; fi`

scalebit.o: scale2x/scalebit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scalebit.o -MD -MP -MF $(DEPDIR)/scalebit.Tpo -c -o scalebit.o `test -f 'scale2x/scalebit.c' || echo '$(srcdir)/'`scale2x/scalebit.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/scalebit.Tpo $(DEPDIR)/scalebit.Po
#	$(AM_V_CC) \
#	source='scale2x/scalebit.c' object='scalebit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scalebit.o `test -f 'scale2x/scalebit.c' || echo '$(srcdir)/'`scale2x/scalebit.c

scalebit.obj: scale2x/scalebit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT scalebit.obj -MD -MP -MF $(DEPDIR)/scalebit.Tpo -c -o scalebit.obj `if test -f 'scale2x/scalebit.c'; then $(CYGPATH_W) 'scale2x/scalebit.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scalebit.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/scalebit.Tpo $(DEPDIR)/scalebit.Po
#	$(AM_V_CC) \
#	source='scale2x/scalebit.c' object='scalebit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o scalebit.obj `if test -f 'scale2x/scalebit.c'; then $(CYGPATH_W) 'scale2x/scalebit.c'; else $(CYGPATH_W) '$(srcdir)/scale2x/scalebit.c'; fi`

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.s.o:
	$(AM_V_CCAS) \
	$(CCASCOMPILE) -c -o $@ $<

.s.obj:
	$(AM_V_CCAS) \
	$(CCASCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

drz80.o: drz80/drz80.s
	$(AM_V_CCAS) \
	$(CCAS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o drz80.o `test -f 'drz80/drz80.s' || echo '$(srcdir)/'`drz80/drz80.s

drz80.obj: drz80/drz80.s
	$(AM_V_CCAS) \
	$(CCAS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o drz80.obj `if test -f 'drz80/drz80.s'; then $(CYGPATH_W) 'drz80/drz80.s'; else $(CYGPATH_W) '$(srcdir)/drz80/drz80.s'; fi`
install-man1: $(man_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
	@list=''; test -n "$(man1dir)" || exit 0; \
	{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	test -z "$$files" || { \
	  echo " ( cd '$(DESTDIR)$(man1dir)' && rm -f" $$files ")"; \
	  cd "$(DESTDIR)$(man1dir)" && rm -f $$files; }
install-man5: $(man_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man5dir)" || $(MKDIR_P) "$(DESTDIR)$(man5dir)"
	@list=''; test -n "$(man5dir)" || exit 0; \
	{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.5[a-z]*$$/p'; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^5][0-9a-z]*$$,5,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man5dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man5dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man5dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man5dir)" || exit $$?; }; \
	done; }

uninstall-man5:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man5dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.5[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^5][0-9a-z]*$$,5,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	test -z "$$files" || { \
	  echo " ( cd '$(DESTDIR)$(man5dir)' && rm -f" $$files ")"; \
	  cd "$(DESTDIR)$(man5dir)" && rm -f $$files; }

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(MANS)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(man5dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-man

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man: install-man1 install-man5

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1 uninstall-man5

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-binPROGRAMS \
	clean-generic ctags ctags-recursive dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-man5 install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-binPROGRAMS uninstall-man \
	uninstall-man1 uninstall-man5


.asm.$(OBJEXT):
	 -f  -o $@ -- $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
